site_name: My Docs
site_description: This documentation will cover installation, configuration, and usage details.
site_author: Veronica Phillip

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "ðŸ”—"

nav:
  - Home: index.md
  - 'welcome to mkdocs:' welcome-to-mkdocs.md
  - 'image folder:' image.md
